# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        association_card:
            quality: 75
            format: png
            filters:
                thumbnail:
                    size: [ 96, 96 ]
                    mode: inset
                background:
                    color: '#fff'
                    size: [ 96, 96 ]
                    position: center
            post_processors:
                optipng: { strip_all: true, level: 5 }
        association_card_png:
            quality: 75
            filters:
                thumbnail:
                    size: [ 300, 150 ]
                    mode: inset
            post_processors:
                optipng: { strip_all: true, level: 5 }