services:

###> symfony/mailer ###
  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT}_mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Boite mail
    networks:
      symfony:
        ipv4_address: 172.${PROJECT_IP_NETWORK}.1.4 # Mise en place d'une adresse IP_V4 fixe pour le container
###< symfony/mailer ###
